name: BOAT
on:
  push:
    branches:
      - master
      - "**"
  pull_request:
    branches: [ master ]

jobs:
  main:
    if: "!contains(github.event.head_commit.message, '[version bump]')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Build Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2
          restore-keys: |
            ${{ runner.os }}-m2
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

#      - name: Get version from POM
#        env:
#          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
#        run: |
#          VERSION_PARTS=($(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | tr "." "\n"))
#          echo "::set-env name=MAJOR::${VERSION_PARTS[0]}"
#          echo "::set-env name=MINOR::${VERSION_PARTS[1]}"
#          echo "::set-env name=PATCH::${VERSION_PARTS[2]}"
#
#      - name: Setup release version
#        if: contains(github.ref, 'master')
#        env:
#          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
#        run: |
#          NEW_VERSION="$((MAJOR)).$((MINOR+1)).0"
#          echo "::set-env name=NEW_VERSION::${NEW_VERSION}"
#
#      - name: Setup PR version
#        if: contains(github.ref, '/pull/')
#        env:
#          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
#        run: |
#          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}-PR-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"
#          echo "::set-env name=NEW_VERSION::${NEW_VERSION}"
#
#      - name: Update POM Version
#        run: |
#          echo "New version  is: $NEW_VERSION"
#          mvn versions:set versions:update-child-modules -DnewVersion=${NEW_VERSION} -DprocessAllModules -DgenerateBackupPoms=false

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

      - name: Sending new BOAT into the Maven Ocean
        if: contains(github.ref, 'master')
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}

#      - name: Commit files
#        if: contains(github.ref, 'master')
#        run: |
#         git config --local user.email "action@github.com"
#         git config --local user.name "GitHub Action"
#         git commit -m "[version bump]" -a
#         git tag -a $NEW_VERSION -m "[version bump]"
#
#      - name: Push changes
#        if: contains(github.ref, 'master')
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
